on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system
      run: sudo apt-get -y install cmake r-base
    - name: Build
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX=~/.local
        cmake --build build -j4
        ctest --test-dir build -j4 -V --output-on-failure

  macos:
    runs-on: macos-latest
    env:
      LDFLAGS: -L/opt/homebrew/opt/openblas/lib
      CPPFLAGS: -I/opt/homebrew/opt/openblas/include
    steps:
    - uses: actions/checkout@v4
    - run: brew install swig r
    - run: |
        cmake -DCMAKE_INSTALL_PREFIX=~/.local  .
        make install -j3
        ctest -j3 --output-on-failure --timeout 100 --schedule-random

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
      - name: Uninstall R
        shell: cmd
        run: del /s /q "C:\Program Files\R"
      - name: Install
        run: |
          conda install -y cmake swig r-essentials
          conda list
      - name: Check R
        run: R --version
      - name: Check R2
        shell: cmd
        run: |
          echo "%PATH%"
          R --version
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: cmd
        run: |
          set "LIB=C:\Users\runneradmin\miniconda3\Library\lib;%LIB%"
          set "INCLUDE=C:\Users\runneradmin\miniconda3\Library\include;%INCLUDE%"
          cmake -G Ninja -B . -LAH ^
           -DCMAKE_INSTALL_PREFIX="C:/Users/runneradmin/miniconda3/Library" ^
           -DCMAKE_PREFIX_PATH="C:/Users/runneradmin/miniconda3/Library" ^
           -DR_EXECUTABLE="C:/Users/runneradmin/miniconda3/Lib/R/bin/x64/R.exe" ^
           -DRSCRIPT_EXECUTABLE="C:/Users/runneradmin/miniconda3/Lib/R/bin/x64/Rscript.exe" ^
           -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /W3 /GR /EHsc /WX" || exit 1
          cmake --build . --target install --parallel 2 || exit 1
          ctest --output-on-failure --timeout 100 -E cppcheck -j2 --repeat after-timeout:2 --schedule-random
